import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Header from "@/components/shared/Header";
import ReactQueryProvider from "@/components/shared/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body
          className={`flex flex-col min-h-screen justify-between p-8 font-mono`}
        >
          <Header />
          {children}
          <Navbar />
        </body>
      </html>
    </ReactQueryProvider>
  );
}
