'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/shared/Navbar";
import Header from "@/components/shared/Header";
import ReactQueryProvider from "@/components/shared/ReactQueryProvider";
import { Navbar, ThemeProvider } from "@material-tailwind/react";
import NavbarDefault from "@/components/shared/Navbar";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const title = "Language Cards"

  useEffect(() => {
    if (title) document.title = title
  }, [title])
  return (
    <ThemeProvider>
      <ReactQueryProvider>
        <html lang="en">
          <body
            className={`flex flex-col min-h-screen p-8 font-mono`}
          >
            <link rel="icon" href="./logo.svg" sizes="any" />
            <NavbarDefault />
            {/* <Header /> */}
            {children}
          </body>
        </html>
      </ReactQueryProvider>
    </ThemeProvider>
  );
}
